### ISSUE TITLE
Assign labels not working

### ISSUE THREAD

**Issue by hawkeye116477** [bkeepers/workflow#18]
I tried this, for first this won't work, so I added .payload before .issue and works, even closing works, but assigning labels not work.
```
on('issues.opened')
  .filter(context => !context.payload.issue.body.match(/### Steps to Reproduce/)
       || context.payload.issue.body.includes('- [ ]'))
  .comment(contents('.github/MISSING_ISSUE_TEMPLATE_AUTOREPLY.md'))
  .label('insufficient-info')
  .close();
```

**Comment by LeoColomb** [comment]
Thanks for your report @hawkeye116477!

> so I added .payload before .issue and works

You're right, it looks like it's missing on the documentation. Would you aim creating a pull request to fix this? Thx! 👍 

> assigning labels not work

That's odd... Do you have any error or output to provide?

**Comment by hawkeye116477** [comment]
@LeoColomb 
```
[90m08:25:01.180Z[39m [31mERROR[39m event: [36mEmpty value for parameter 'labels': undefined[39m[90m (id=50de2130-4474-11e8-850e-17b509bf38fb)[39m

[90m  HttpError: Empty value for parameter 'labels': undefined

      at Object.keys.forEach.parameterName (/rbd/pnpm-volume/ed6b9217-a417-408a-a6f9-50b7f23d5f33/node_modules/.registry.npmjs.org/@octokit/rest/15.2.0/node_modules/@octokit/rest/lib/plugins/endpoint-methods/validate.js:27:13)

      at Array.forEach (<anonymous>)

      at validate (/rbd/pnpm-volume/ed6b9217-a417-408a-a6f9-50b7f23d5f33/node_modules/.registry.npmjs.org/@octokit/rest/15.2.0/node_modules/@octokit/rest/lib/plugins/endpoint-methods/validate.js:9:31)

      at <anonymous>

      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
